[package]
name = "okv-slate"
description = "Pinned SlateDB adaptation layer for objectKV"
edition.workspace = true
license.workspace = true
publish = false
rust-version.workspace = true
version.workspace = true

[dependencies]
async-trait.workspace = true
bytes.workspace = true
futures-util.workspace = true
okv-model.workspace = true
object_store.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
slatedb.workspace = true
sysinfo.workspace = true
tempfile.workspace = true
tokio.workspace = true
tokio-util.workspace = true

[lints]
workspace = true
